// <auto-generated />
using Storage.Database.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190211123619_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Database.Table.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Displayname");

                    b.Property<string>("FirstName");

                    b.Property<string>("ImgFilePath");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer","Service");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Displayname = "Test Tester",
                            FirstName = "Test",
                            ImgFilePath = "",
                            LastName = "Tester",
                            Password = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
